name: bip85_entropy
description: A pure Dart implementation of BIP85 - Deterministic Entropy
version: 1.0.0
repository: https://github.com/ethicnology/dart-bip85-entropy
homepage: https://github.com/ethicnology/dart-bip85-entropy

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  bip32_keys: ^3.1.1
  pointycastle: ^3.9.1
  convert: ^3.1.1
  bip39_mnemonic: ^4.0.1
  base85: ^1.0.4
  

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.6
